global using System.ComponentModel.DataAnnotations;
global using AeonRegistryAPI.Extensions;
global using AeonRegistryAPI.Models.Response;
global using AeonRegistryAPI.Data;
global using AeonRegistryAPI.Models;
global using AeonRegistryAPI.Middleware;
global using AeonRegistryAPI.Enums;
global using AeonRegistryAPI.Models.Request;
global using AeonRegistryAPI.Services.Interfaces;
